### ISSUE TITLE
Faltan algunos Avengers

### ISSUE THREAD

**Issue by CIRKL0N3** [Edgar-Hernandez01/avengers-practice#3]
# Request.

Por favor agregar a Nick Fury y Cap Marvel a la lista de los avengers.

- [x] Nick Fury.
- [x] #4

**Comment by Edgar-Hernandez01** [comment]
Se ha agregado a Nick Fury. 
Capitana Marvel ya se encontraba en la lista.

**Comment by CIRKL0N3** [comment]
Se ha agregado a Nick Fury.
Capitana Marvel ya se encontraba en la lista.
